### ISSUE TITLE
Specifics of RAG Setting?

### ISSUE THREAD

**Issue by jw-sohn** [Itaymanes/K-QA#6]
Dear Authors (@Itaymanes),

Thank you for your excellent work and for sharing your research.

I have a few questions regarding the Retrieval-Augmented Generation (RAG) settings used in the study:

1. What type of retriever was implemented in your experiments?

2. Which corpus or datasets were used for retrieval? I noticed that Mayo Clinic and NHS.uk were mentioned as examples, but I would appreciate more detailed information.

**Comment by Itaymanes** [comment]
Hi @ahwatnow,

Thanks for reaching out.
Could you clarify what you mean by "type of retriever"?
Let’s delve into the details in private—please email me.
